name = "youtube-transcript-mcp"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "TRANSCRIPT_CACHE"
id = "9aefd7cd2a1f433fb537f596dc14ff03"

# Remove any durable_objects configuration
# Remove any environment variables related to GitHub OAuth

[vars]
# Add any environment variables here if needed